<?php
$pageTitle = 'Detail Transaksi Keuangan';
$activeMenu = 'keuangan';
$breadcrumb = 'Kas & Keuangan / Detail';
require_once __DIR__ . '/../../includes/header_admin.php';
$pdo = getDB();
$id = (int) ($_GET['id'] ?? 0);
$stmt = $pdo->prepare('SELECT tk.*, kk.kode AS kategori_kode, kk.nama AS kategori, kk.tipe, a.nama AS dibuat_oleh FROM transaksi_keuangan tk INNER JOIN kategori_keuangan kk ON kk.id = tk.kategori_id LEFT JOIN admin a ON a.id = tk.created_by WHERE tk.id = :id LIMIT 1');
$stmt->execute([':id' => $id]);
$transaction = $stmt->fetch();
if (!$transaction) { flash_set('error', 'Transaksi keuangan tidak ditemukan.'); redirect('/admin/keuangan/index.php'); }
$categories = $pdo->query('SELECT id, kode, nama, tipe FROM kategori_keuangan ORDER BY tipe ASC, nama ASC')->fetchAll();
$methods = ['CASH', 'TRANSFER', 'GIRO', 'KARTU', 'LAINNYA'];
?>

<div class="ab-detail-layout"><div class="ab-detail-panel"><div class="panel-head"><h3>Data Transaksi</h3><div class="detail-actions"><button type="button" class="btn btn-edit" data-open-finance-detail>Edit</button><form method="post" action="<?= BASE_URL ?>/admin/keuangan/index.php" onsubmit="return confirm('Hapus transaksi keuangan ini?');" style="display:inline;"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $transaction['id'] ?>"><button type="submit" class="btn btn-delete">Hapus</button></form></div></div><table class="detail-table"><tr><th>Nomor Transaksi</th><td><?= e($transaction['nomor_transaksi']) ?></td></tr><tr><th>Tanggal</th><td><?= e(tanggal_indo($transaction['tanggal'])) ?></td></tr><tr><th>Kategori</th><td><?= e($transaction['kategori_kode'] . ' - ' . $transaction['kategori']) ?></td></tr><tr><th>Tipe</th><td><span class="badge <?= $transaction['tipe'] === 'PENDAPATAN' ? 'badge-ok' : 'badge-danger' ?>"><?= e($transaction['tipe']) ?></span></td></tr><tr><th>Metode Pembayaran</th><td><?= e($transaction['metode_pembayaran'] ?: '-') ?></td></tr><tr><th>Referensi</th><td><?= e($transaction['referensi'] ?: '-') ?></td></tr><tr><th>Dibuat Oleh</th><td><?= e($transaction['dibuat_oleh'] ?: '-') ?></td></tr><tr><th>Keterangan</th><td><?= e($transaction['keterangan'] ?: '-') ?></td></tr></table></div><div class="ab-detail-panel"><div class="panel-head"><h3>Nominal Transaksi</h3></div><div class="unit-summary"><div class="summary-row"><span class="label">Jenis Arus Kas</span><span class="value"><?= e($transaction['tipe']) ?></span></div><div class="summary-row"><span class="label"><strong>Nominal</strong></span><span class="value"><strong><?= rupiah($transaction['nominal']) ?></strong></span></div></div></div></div>

<div class="modal-backdrop" id="finance-detail-modal" aria-hidden="true"><div class="modal-box" role="dialog" aria-modal="true" aria-labelledby="finance-detail-title"><div class="modal-header"><h3 id="finance-detail-title">Edit Transaksi Keuangan</h3><button type="button" class="modal-close" data-close-finance-detail aria-label="Tutup">Ã—</button></div><form method="post" action="<?= BASE_URL ?>/admin/keuangan/index.php"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= (int) $transaction['id'] ?>"><div class="modal-grid"><div class="field"><label for="detail-number">Nomor Transaksi</label><input id="detail-number" name="nomor_transaksi" value="<?= e($transaction['nomor_transaksi']) ?>" required></div><div class="field"><label for="detail-date">Tanggal</label><input id="detail-date" name="tanggal" type="date" value="<?= e($transaction['tanggal']) ?>" required></div><div class="field field-full"><label for="detail-category">Kategori Keuangan</label><select id="detail-category" name="kategori_id" required><?php foreach ($categories as $category): ?><option value="<?= (int) $category['id'] ?>" <?= (int) $category['id'] === (int) $transaction['kategori_id'] ? 'selected' : '' ?>><?= e($category['tipe'] . ' - ' . $category['kode'] . ' - ' . $category['nama']) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-amount">Nominal</label><input id="detail-amount" name="nominal" type="number" min="0.01" step="0.01" value="<?= (float) $transaction['nominal'] ?>" required></div><div class="field"><label for="detail-method">Metode Pembayaran</label><select id="detail-method" name="metode_pembayaran"><?php foreach ($methods as $method): ?><option value="<?= e($method) ?>" <?= $transaction['metode_pembayaran'] === $method ? 'selected' : '' ?>><?= e($method) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-reference">Referensi</label><input id="detail-reference" name="referensi" value="<?= e($transaction['referensi'] ?? '') ?>"></div><div class="field field-full"><label for="detail-note">Keterangan</label><textarea id="detail-note" name="keterangan" rows="3"><?= e($transaction['keterangan'] ?? '') ?></textarea></div></div><div class="modal-actions"><button type="button" class="btn btn-outline-dark btn-sm" data-close-finance-detail>Batal</button><button type="submit" class="btn btn-amber btn-sm">Simpan</button></div></form></div></div>

<script>
(function () { const modal = document.getElementById('finance-detail-modal'); if (!modal) return; const close = () => { modal.classList.remove('show'); modal.setAttribute('aria-hidden', 'true'); }; document.querySelector('[data-open-finance-detail]')?.addEventListener('click', () => { modal.classList.add('show'); modal.setAttribute('aria-hidden', 'false'); }); document.querySelectorAll('[data-close-finance-detail]').forEach((button) => button.addEventListener('click', close)); modal.addEventListener('click', (event) => { if (event.target === modal) close(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && modal.classList.contains('show')) close(); }); })();
</script>

<?php require __DIR__ . '/../../includes/footer_admin.php'; ?>

