<?php
$pageTitle = 'Detail Pembelian';
$activeMenu = 'pembelian';
$breadcrumb = 'Transaksi / Pembelian / Detail';
require_once __DIR__ . '/../../includes/header_admin.php';
$pdo = getDB();
$id = (int) ($_GET['id'] ?? 0);
$stmt = $pdo->prepare('SELECT po.*, s.kode AS supplier_kode, s.nama AS supplier FROM pembelian_sparepart po INNER JOIN supplier s ON s.id = po.supplier_id WHERE po.id = :id LIMIT 1');
$stmt->execute([':id' => $id]);
$purchase = $stmt->fetch();
if (!$purchase) { flash_set('error', 'Transaksi pembelian tidak ditemukan.'); redirect('/admin/pembelian/index.php'); }
$detailStmt = $pdo->prepare('SELECT pd.*, sp.kode, sp.nama, sp.satuan FROM pembelian_sparepart_detail pd INNER JOIN sparepart sp ON sp.id = pd.sparepart_id WHERE pd.pembelian_id = :id ORDER BY pd.id ASC');
$detailStmt->execute([':id' => $id]);
$details = $detailStmt->fetchAll();
$suppliers = $pdo->query("SELECT id, kode, nama FROM supplier WHERE status = 'Aktif' ORDER BY nama ASC")->fetchAll();
$parts = $pdo->query('SELECT id, kode, nama, satuan FROM sparepart ORDER BY nama ASC')->fetchAll();
$statuses = ['DRAFT', 'PROSES', 'SELESAI', 'CANCELLED'];
?>

<div class="ab-detail-layout">
  <div class="ab-detail-panel"><div class="panel-head"><h3>Data Pembelian</h3><div class="detail-actions"><button type="button" class="btn btn-edit" data-open-purchase-detail>Edit</button><form method="post" action="<?= BASE_URL ?>/admin/pembelian/index.php" onsubmit="return confirm('Hapus transaksi pembelian ini?');" style="display:inline;"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $purchase['id'] ?>"><button type="submit" class="btn btn-delete">Hapus</button></form></div></div><table class="detail-table"><tr><th>Nomor Pembelian</th><td><?= e($purchase['nomor_pembelian']) ?></td></tr><tr><th>Tanggal</th><td><?= e(tanggal_indo($purchase['tanggal'])) ?></td></tr><tr><th>Supplier</th><td><?= e($purchase['supplier_kode'] . ' - ' . $purchase['supplier']) ?></td></tr><tr><th>Status</th><td><span class="badge <?= status_badge_class($purchase['status']) ?>"><?= e($purchase['status']) ?></span></td></tr><tr><th>Keterangan</th><td><?= e($purchase['keterangan'] ?: '-') ?></td></tr></table></div>
  <div class="ab-detail-panel"><div class="panel-head"><h3>Item Pembelian</h3></div><table class="detail-table"><thead><tr><th>Item</th><th>Qty</th><th>Harga</th><th>Diskon</th><th>Subtotal</th></tr></thead><tbody><?php foreach ($details as $detail): ?><tr><td><strong><?= e($detail['kode']) ?></strong><br><?= e($detail['nama']) ?></td><td><?= e((string) $detail['qty']) . ' ' . e($detail['satuan']) ?></td><td><?= rupiah($detail['harga']) ?></td><td><?= rupiah($detail['diskon']) ?></td><td><?= rupiah($detail['subtotal']) ?></td></tr><?php endforeach; ?><tr><th colspan="4">Total</th><td><strong><?= rupiah($purchase['total']) ?></strong></td></tr></tbody></table></div>
</div>

<div class="modal-backdrop" id="purchase-detail-modal" aria-hidden="true"><div class="modal-box" role="dialog" aria-modal="true" aria-labelledby="purchase-detail-title"><div class="modal-header"><h3 id="purchase-detail-title">Edit Pembelian</h3><button type="button" class="modal-close" data-close-purchase-detail aria-label="Tutup">Ã—</button></div><form method="post" action="<?= BASE_URL ?>/admin/pembelian/index.php"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= (int) $purchase['id'] ?>"><div class="modal-grid"><div class="field"><label for="detail-number">Nomor Pembelian</label><input id="detail-number" name="nomor_pembelian" value="<?= e($purchase['nomor_pembelian']) ?>" required></div><div class="field"><label for="detail-date">Tanggal</label><input id="detail-date" name="tanggal" type="date" value="<?= e($purchase['tanggal']) ?>" required></div><div class="field"><label for="detail-supplier">Supplier</label><select id="detail-supplier" name="supplier_id" required><?php foreach ($suppliers as $supplier): ?><option value="<?= (int) $supplier['id'] ?>" <?= (int) $supplier['id'] === (int) $purchase['supplier_id'] ? 'selected' : '' ?>><?= e($supplier['kode'] . ' - ' . $supplier['nama']) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-status">Status</label><select id="detail-status" name="status"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= $purchase['status'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></div><div class="field field-full"><label>Item Pembelian</label><div id="detail-purchase-items"></div><button type="button" class="btn btn-outline-dark btn-sm" id="add-detail-purchase-item">+ Tambah Item</button></div><div class="field field-full"><label for="detail-note">Keterangan</label><textarea id="detail-note" name="keterangan" rows="3"><?= e($purchase['keterangan'] ?? '') ?></textarea></div></div><div class="modal-actions"><button type="button" class="btn btn-outline-dark btn-sm" data-close-purchase-detail>Batal</button><button type="submit" class="btn btn-amber btn-sm">Simpan</button></div></form></div></div>

<script>
(function () { const modal = document.getElementById('purchase-detail-modal'); const container = document.getElementById('detail-purchase-items'); const add = document.getElementById('add-detail-purchase-item'); const parts = <?= json_encode($parts, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT) ?>; const details = <?= json_encode($details, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT) ?>; if (!modal) return; const makeRow = (data = {}) => { const row = document.createElement('div'); row.style.cssText = 'display:grid;grid-template-columns:2fr .8fr 1.2fr 1.2fr auto;gap:8px;margin-bottom:10px;align-items:end'; row.innerHTML = '<select name="sparepart_id[]" required><option value="">Pilih item</option>' + parts.map((part) => '<option value="' + part.id + '" ' + (String(data.sparepart_id || '') === String(part.id) ? 'selected' : '') + '>' + part.kode + ' - ' + part.nama + '</option>').join('') + '</select><input name="qty[]" type="number" min="0.01" step="0.01" value="' + (data.qty || 1) + '" required><input name="harga[]" type="number" min="0" step="0.01" value="' + (data.harga || 0) + '" required><input name="diskon[]" type="number" min="0" step="0.01" value="' + (data.diskon || 0) + '"><button type="button" class="mini-btn mini-btn-delete remove-detail-item">Hapus</button>'; row.querySelector('.remove-detail-item').addEventListener('click', () => row.remove()); container.appendChild(row); }; const close = () => { modal.classList.remove('show'); modal.setAttribute('aria-hidden', 'true'); }; document.querySelector('[data-open-purchase-detail]')?.addEventListener('click', () => { modal.classList.add('show'); modal.setAttribute('aria-hidden', 'false'); }); document.querySelectorAll('[data-close-purchase-detail]').forEach((button) => button.addEventListener('click', close)); add.addEventListener('click', () => makeRow()); modal.addEventListener('click', (event) => { if (event.target === modal) close(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && modal.classList.contains('show')) close(); }); details.forEach((detail) => makeRow(detail)); })();
</script>

<?php require __DIR__ . '/../../includes/footer_admin.php'; ?>

