<?php 
include '../../koneksi.php';

$pembelian_id = $_POST['pembelian_id'];
$sparepart_id = $_POST['sparepart_id'];
$qty = $_POST['qty'];
$harga = $_POST['harga'];
$diskon = empty($_POST['diskon']) ? 0 : $_POST['diskon'];
$keterangan = "";

// Cek apakah item sudah ada di PO ini, jika ya, tambahkan QTY nya
$cek = mysqli_query($koneksi, "SELECT * FROM pembelian_sparepart_detail WHERE pembelian_id='$pembelian_id' AND sparepart_id='$sparepart_id'");
if(mysqli_num_rows($cek) > 0){
    $c = mysqli_fetch_assoc($cek);
    $new_qty = $c['qty'] + $qty;
    mysqli_query($koneksi, "UPDATE pembelian_sparepart_detail SET qty='$new_qty', harga='$harga', diskon='$diskon' WHERE id='".$c['id']."'");
} else {
    // Insert new item
    // Subtotal will be calculated automatically by MariaDB (STORED GENERATED) if configured that way, 
    // but just in case it is NOT natively generated by the DB in this version, we will not specify it in the insert if it's virtual.
    // Wait, the schema says: subtotal decimal(18,2) YES NULL STORED GENERATED.
    // So we don't need to insert 'subtotal'.
    mysqli_query($koneksi, "INSERT INTO pembelian_sparepart_detail (pembelian_id, sparepart_id, qty, harga, diskon, keterangan, created_at, updated_at) 
                            VALUES ('$pembelian_id', '$sparepart_id', '$qty', '$harga', '$diskon', '$keterangan', NOW(), NOW())") or die(mysqli_error($koneksi));
}

// Update the header total
$sum = mysqli_query($koneksi, "SELECT SUM(subtotal) as total FROM pembelian_sparepart_detail WHERE pembelian_id='$pembelian_id'");
$s = mysqli_fetch_assoc($sum);
$total = $s['total'];
mysqli_query($koneksi, "UPDATE pembelian_sparepart SET total='$total' WHERE id='$pembelian_id'");

header("location:../pembelian_detail.php?id=" . $pembelian_id);
?>
