<?php
$pageTitle = 'Detail Pelanggan';
$activeMenu = 'customer';
$breadcrumb = 'Rekanan / Pelanggan / Detail';
require_once __DIR__ . '/../../includes/header_admin.php';
$pdo = getDB();
$id = (int) ($_GET['id'] ?? 0);
$stmt = $pdo->prepare('SELECT * FROM customer WHERE id = :id LIMIT 1');
$stmt->execute([':id' => $id]);
$customer = $stmt->fetch();
if (!$customer) { flash_set('error', 'Data pelanggan tidak ditemukan.'); redirect('/admin/customer/index.php'); }
$salesStmt = $pdo->prepare('SELECT p.nomor_penjualan, p.tanggal, p.total, p.status, ab.kode, ab.tipe FROM penjualan p LEFT JOIN penjualan_detail pd ON pd.penjualan_id = p.id LEFT JOIN alat_berat ab ON ab.id = pd.alat_berat_id WHERE p.customer_id = :id ORDER BY p.tanggal DESC, p.id DESC');
$salesStmt->execute([':id' => $id]);
$sales = $salesStmt->fetchAll();
$types = ['Individu', 'Perusahaan'];
$statuses = ['Baru', 'Reguler', 'Blacklist'];
?>

<div class="ab-detail-layout"><div class="ab-detail-panel"><div class="panel-head"><h3>Data Pelanggan</h3><div class="detail-actions"><button type="button" class="btn btn-edit" data-open-customer-detail>Edit</button><form method="post" action="<?= BASE_URL ?>/admin/customer/index.php" onsubmit="return confirm('Hapus pelanggan ini?');" style="display:inline;"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $customer['id'] ?>"><button type="submit" class="btn btn-delete">Hapus</button></form></div></div><table class="detail-table"><tr><th>Kode</th><td><?= e($customer['kode']) ?></td></tr><tr><th>Nama</th><td><?= e($customer['nama']) ?></td></tr><tr><th>Jenis</th><td><?= e($customer['jenis_pelanggan']) ?></td></tr><tr><th>Nama Perusahaan</th><td><?= e($customer['nama_perusahaan'] ?: '-') ?></td></tr><tr><th>Contact Person</th><td><?= e($customer['contact_person'] ?: '-') ?></td></tr><tr><th>Telepon</th><td><?= e($customer['telepon'] ?: '-') ?></td></tr><tr><th>Email</th><td><?= e($customer['email'] ?: '-') ?></td></tr><tr><th>Alamat</th><td><?= e($customer['alamat'] ?: '-') ?></td></tr><tr><th>Status</th><td><span class="badge <?= status_badge_class($customer['status_pelanggan']) ?>"><?= e($customer['status_pelanggan']) ?></span></td></tr><tr><th>Kebijakan DP</th><td><?= number_format((float) $customer['kebijakan_dp'], 2, ',', '.') ?>%</td></tr><tr><th>Keterangan</th><td><?= e($customer['keterangan'] ?: '-') ?></td></tr></table></div>
<div class="ab-detail-panel"><div class="panel-head"><h3>Riwayat Penjualan</h3></div><?php if (empty($sales)): ?><div class="empty-state"><p>Belum ada transaksi penjualan.</p></div><?php else: ?><table class="detail-table"><thead><tr><th>Nomor</th><th>Tanggal</th><th>Unit</th><th>Status</th><th>Total</th></tr></thead><tbody><?php foreach ($sales as $sale): ?><tr><td><?= e($sale['nomor_penjualan']) ?></td><td><?= e(tanggal_indo($sale['tanggal'])) ?></td><td><?= e(($sale['kode'] ?: '-') . ' - ' . ($sale['tipe'] ?: '-')) ?></td><td><span class="badge <?= status_badge_class($sale['status']) ?>"><?= e($sale['status']) ?></span></td><td><?= rupiah($sale['total']) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></div>

<div class="modal-backdrop" id="customer-detail-modal" aria-hidden="true"><div class="modal-box" role="dialog" aria-modal="true" aria-labelledby="customer-detail-title"><div class="modal-header"><h3 id="customer-detail-title">Edit Pelanggan</h3><button type="button" class="modal-close" data-close-customer-detail aria-label="Tutup">Ã—</button></div><form method="post" action="<?= BASE_URL ?>/admin/customer/index.php"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= (int) $customer['id'] ?>"><div class="modal-grid"><div class="field"><label for="detail-code">Kode Pelanggan</label><input id="detail-code" name="kode" value="<?= e($customer['kode']) ?>" required></div><div class="field"><label for="detail-name">Nama</label><input id="detail-name" name="nama" value="<?= e($customer['nama']) ?>" required></div><div class="field"><label for="detail-type">Jenis Pelanggan</label><select id="detail-type" name="jenis_pelanggan"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>" <?= $customer['jenis_pelanggan'] === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-company">Nama Perusahaan</label><input id="detail-company" name="nama_perusahaan" value="<?= e($customer['nama_perusahaan'] ?? '') ?>"></div><div class="field"><label for="detail-phone">Telepon</label><input id="detail-phone" name="telepon" value="<?= e($customer['telepon'] ?? '') ?>"></div><div class="field"><label for="detail-email">Email</label><input id="detail-email" name="email" type="email" value="<?= e($customer['email'] ?? '') ?>"></div><div class="field"><label for="detail-contact">Contact Person</label><input id="detail-contact" name="contact_person" value="<?= e($customer['contact_person'] ?? '') ?>"></div><div class="field"><label for="detail-dp">Kebijakan DP (%)</label><input id="detail-dp" name="kebijakan_dp" type="number" min="0" max="100" step="0.01" value="<?= (float) $customer['kebijakan_dp'] ?>"></div><div class="field field-full"><label for="detail-address">Alamat</label><textarea id="detail-address" name="alamat" rows="2"><?= e($customer['alamat'] ?? '') ?></textarea></div><div class="field"><label for="detail-status">Status</label><select id="detail-status" name="status_pelanggan"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= $customer['status_pelanggan'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-note">Keterangan</label><textarea id="detail-note" name="keterangan" rows="2"><?= e($customer['keterangan'] ?? '') ?></textarea></div></div><div class="modal-actions"><button type="button" class="btn btn-outline-dark btn-sm" data-close-customer-detail>Batal</button><button type="submit" class="btn btn-amber btn-sm">Simpan</button></div></form></div></div>

<script>
(function () { const modal = document.getElementById('customer-detail-modal'); if (!modal) return; const close = () => { modal.classList.remove('show'); modal.setAttribute('aria-hidden', 'true'); }; document.querySelector('[data-open-customer-detail]')?.addEventListener('click', () => { modal.classList.add('show'); modal.setAttribute('aria-hidden', 'false'); }); document.querySelectorAll('[data-close-customer-detail]').forEach((button) => button.addEventListener('click', close)); modal.addEventListener('click', (event) => { if (event.target === modal) close(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && modal.classList.contains('show')) close(); }); })();
</script>

<?php require __DIR__ . '/../../includes/footer_admin.php'; ?>

