<?php
$pageTitle = 'Detail Supplier';
$activeMenu = 'supplier';
$breadcrumb = 'Rekanan / Supplier / Detail';
require_once __DIR__ . '/../../includes/header_admin.php';
$pdo = getDB();
$id = (int) ($_GET['id'] ?? 0);
$stmt = $pdo->prepare('SELECT * FROM supplier WHERE id = :id LIMIT 1');
$stmt->execute([':id' => $id]);
$supplier = $stmt->fetch();
if (!$supplier) { flash_set('error', 'Data supplier tidak ditemukan.'); redirect('/admin/supplier/index.php'); }
$purchaseStmt = $pdo->prepare('SELECT nomor_pembelian, tanggal, total, status FROM pembelian_sparepart WHERE supplier_id = :id ORDER BY tanggal DESC, id DESC');
$purchaseStmt->execute([':id' => $id]);
$purchases = $purchaseStmt->fetchAll();
$statuses = ['Aktif', 'Tidak Aktif'];
?>

<div class="ab-detail-layout"><div class="ab-detail-panel"><div class="panel-head"><h3>Data Supplier</h3><div class="detail-actions"><button type="button" class="btn btn-edit" data-open-supplier-detail>Edit</button><form method="post" action="<?= BASE_URL ?>/admin/supplier/index.php" onsubmit="return confirm('Hapus supplier ini?');" style="display:inline;"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $supplier['id'] ?>"><button type="submit" class="btn btn-delete">Hapus</button></form></div></div><table class="detail-table"><tr><th>Kode</th><td><?= e($supplier['kode']) ?></td></tr><tr><th>Nama</th><td><?= e($supplier['nama']) ?></td></tr><tr><th>Status</th><td><span class="badge <?= status_badge_class($supplier['status']) ?>"><?= e($supplier['status']) ?></span></td></tr><tr><th>Negara</th><td><?= e($supplier['negara'] ?: '-') ?></td></tr><tr><th>Alamat</th><td><?= e($supplier['alamat'] ?: '-') ?></td></tr><tr><th>Telepon</th><td><?= e($supplier['telepon'] ?: '-') ?></td></tr><tr><th>Email</th><td><?= e($supplier['email'] ?: '-') ?></td></tr><tr><th>Contact Person</th><td><?= e($supplier['contact_person'] ?: '-') ?></td></tr><tr><th>Keterangan</th><td><?= e($supplier['keterangan'] ?: '-') ?></td></tr></table></div><div class="ab-detail-panel"><div class="panel-head"><h3>Riwayat Pembelian</h3></div><?php if (empty($purchases)): ?><div class="empty-state"><p>Belum ada transaksi pembelian.</p></div><?php else: ?><table class="detail-table"><thead><tr><th>Nomor</th><th>Tanggal</th><th>Status</th><th>Total</th></tr></thead><tbody><?php foreach ($purchases as $purchase): ?><tr><td><?= e($purchase['nomor_pembelian']) ?></td><td><?= e(tanggal_indo($purchase['tanggal'])) ?></td><td><span class="badge <?= status_badge_class($purchase['status']) ?>"><?= e($purchase['status']) ?></span></td><td><?= rupiah($purchase['total']) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></div>

<div class="modal-backdrop" id="supplier-detail-modal" aria-hidden="true"><div class="modal-box" role="dialog" aria-modal="true" aria-labelledby="supplier-detail-title"><div class="modal-header"><h3 id="supplier-detail-title">Edit Supplier</h3><button type="button" class="modal-close" data-close-supplier-detail aria-label="Tutup">Ã—</button></div><form method="post" action="<?= BASE_URL ?>/admin/supplier/index.php"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= (int) $supplier['id'] ?>"><div class="modal-grid"><div class="field"><label for="detail-code">Kode Supplier</label><input id="detail-code" name="kode" value="<?= e($supplier['kode']) ?>" required></div><div class="field"><label for="detail-name">Nama Supplier</label><input id="detail-name" name="nama" value="<?= e($supplier['nama']) ?>" required></div><div class="field"><label for="detail-status">Status</label><select id="detail-status" name="status"><?php foreach ($statuses as $status): ?><option value="<?= e($status) ?>" <?= $supplier['status'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></div><div class="field"><label for="detail-country">Negara</label><input id="detail-country" name="negara" value="<?= e($supplier['negara'] ?? '') ?>"></div><div class="field"><label for="detail-phone">Telepon</label><input id="detail-phone" name="telepon" value="<?= e($supplier['telepon'] ?? '') ?>"></div><div class="field"><label for="detail-email">Email</label><input id="detail-email" name="email" type="email" value="<?= e($supplier['email'] ?? '') ?>"></div><div class="field"><label for="detail-contact">Contact Person</label><input id="detail-contact" name="contact_person" value="<?= e($supplier['contact_person'] ?? '') ?>"></div><div class="field field-full"><label for="detail-address">Alamat</label><textarea id="detail-address" name="alamat" rows="2"><?= e($supplier['alamat'] ?? '') ?></textarea></div><div class="field field-full"><label for="detail-note">Keterangan</label><textarea id="detail-note" name="keterangan" rows="3"><?= e($supplier['keterangan'] ?? '') ?></textarea></div></div><div class="modal-actions"><button type="button" class="btn btn-outline-dark btn-sm" data-close-supplier-detail>Batal</button><button type="submit" class="btn btn-amber btn-sm">Simpan</button></div></form></div></div>

<script>
(function () { const modal = document.getElementById('supplier-detail-modal'); if (!modal) return; const close = () => { modal.classList.remove('show'); modal.setAttribute('aria-hidden', 'true'); }; document.querySelector('[data-open-supplier-detail]')?.addEventListener('click', () => { modal.classList.add('show'); modal.setAttribute('aria-hidden', 'false'); }); document.querySelectorAll('[data-close-supplier-detail]').forEach((button) => button.addEventListener('click', close)); modal.addEventListener('click', (event) => { if (event.target === modal) close(); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && modal.classList.contains('show')) close(); }); })();
</script>

<?php require __DIR__ . '/../../includes/footer_admin.php'; ?>

